### ISSUE TITLE
I wanted to play against easy cpu, because i keep loosing but:

### ISSUE THREAD

**Issue by 41pha1** [Tuquyk/pingpong#1]
pygame 2.5.2 (SDL 2.28.3, Python 3.10.11)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\A1pha1\Documents\Python\pingpong\pingpong.py", line 214, in <module>
    animate_cpu()
  File "C:\Users\A1pha1\Documents\Python\pingpong\pingpong.py", line 53, in animate_cpu
    cpu.y += cpu_speed
NameError: name 'cpu_speed' is not defined

oke
Could you also do bigger playfield? And also increase the time between the spawn of the ball in pvp
Thank youuuu :>

**Comment by Tuquyk** [comment]
I've fixed the bug and added a 0.5-second delay between ball spawns in both modes. I've also added another button to choose the size of the playfield. 
Thank you so much for your feedback and suggestions.
